export const POST_ADD_PENDING = 'POST_ADD_PENDING';
export const POST_ADD_FULFILLED = 'POST_ADD_FULFILLED';
export const POST_ADD_REJECTED = 'POST_ADD_REJECTED';

export const GET_ALL_POSTS_PENDING = 'GET_ALL_POSTS_PENDING';
export const GET_ALL_POSTS_FULFILLED = 'GET_ALL_POSTS_FULFILLED';
export const GET_ALL_POSTS_REJECTED = 'GET_ALL_POSTS_REJECTED';

export const GET_POST_FILTERS_PENDING = 'GET_POST_FILTERS_PENDING';
export const GET_POST_FILTERS_FULFILLED = 'GET_POST_FILTERS_FULFILLED';
export const GET_POST_FILTERS_REJECTED = 'GET_POST_FILTERS_REJECTED';
