export const LIKE_ADD_PENDING = 'LIKE_ADD_PENDING';
export const LIKE_ADD_FULFILLED = 'LIKE_ADD_FULFILLED';
export const LIKE_ADD_REJECTED = 'LIKE_ADD_REJECTED';

export const GET_ALL_LIKES_PENDING = 'GET_ALL_LIKES_PENDING';
export const GET_ALL_LIKES_FULFILLED = 'GET_ALL_LIKES_FULFILLED';
export const GET_ALL_LIKES_REJECTED = 'GET_ALL_LIKES_REJECTED';

export const LIKE_UPDATE_PENDING = 'LIKE_UPDATE_PENDING';
export const LIKE_UPDATE_FULFILLED = 'LIKE_UPDATE_FULFILLED';
export const LIKE_UPDATE_REJECTED = 'LIKE_UPDATE_REJECTED';

export const LIKE_DELETE_PENDING = 'LIKE_DELETE_PENDING';
export const LIKE_DELETE_FULFILLED = 'LIKE_DELETE_FULFILLED';
export const LIKE_DELETE_REJECTED = 'LIKE_DELETE_REJECTED';
