export const USER_ADD_PENDING = 'USER_ADD_PENDING';
export const USER_ADD_FULFILLED = 'USER_ADD_FULFILLED';
export const USER_ADD_REJECTED = 'USER_ADD_REJECTED';

export const GET_ALL_USERS_PENDING = 'GET_ALL_USERS_PENDING';
export const GET_ALL_USERS_FULFILLED = 'GET_ALL_USERS_FULFILLED';
export const GET_ALL_USERS_REJECTED = 'GET_ALL_USERS_REJECTED';

export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

export const USER_UPDATE_PENDING = 'USER_UPDATE_PENDING';
export const USER_UPDATE_FULFILLED = 'USER_UPDATE_FULFILLED';
export const USER_UPDATE_REJECTED = 'USER_UPDATE_REJECTED';

export const USER_DELETE_PENDING = 'USER_DELETE_PENDING';
export const USER_DELETE_FULFILLED = 'USER_DELETE_FULFILLED';
export const USER_DELETE_REJECTED = 'USER_DELETE_REJECTED';
