export const WORKER_ADD_PENDING = 'WORKER_ADD_PENDING';
export const WORKER_ADD_FULFILLED = 'WORKER_ADD_FULFILLED';
export const WORKER_ADD_REJECTED = 'WORKER_ADD_REJECTED';

export const GET_ALL_WORKERS_PENDING = 'GET_ALL_WORKERS_PENDING';
export const GET_ALL_WORKERS_FULFILLED = 'GET_ALL_WORKERS_FULFILLED';
export const GET_ALL_WORKERS_REJECTED = 'GET_ALL_WORKERS_REJECTED';

export const GET_WORKER_PENDING = 'GET_WORKER_PENDING';
export const GET_WORKER_FULFILLED = 'GET_WORKER_FULFILLED';
export const GET_WORKER_REJECTED = 'GET_WORKER_REJECTED';

export const WORKER_UPDATE_PENDING = 'WORKER_UPDATE_PENDING';
export const WORKER_UPDATE_FULFILLED = 'WORKER_UPDATE_FULFILLED';
export const WORKER_UPDATE_REJECTED = 'WORKER_UPDATE_REJECTED';

export const WORKER_DELETE_PENDING = 'WORKER_DELETE_PENDING';
export const WORKER_DELETE_FULFILLED = 'WORKER_DELETE_FULFILLED';
export const WORKER_DELETE_REJECTED = 'WORKER_DELETE_REJECTED';

export const WORKER_IMAGE_ADD_PENDING = 'WORKER_IMAGE_ADD_PENDING';
export const WORKER_IMAGE_ADD_FULFILLED = 'WORKER_IMAGE_ADD_FULFILLED';
export const WORKER_IMAGE_ADD_REJECTED = 'WORKER_IMAGE_ADD_REJECTED';
